title: "Mon blog"
description: "Explorations croisées entre la chimie, la data science"
author: "Ton Nom"
theme: minima

# Navigation (menu en haut)
minima:
  navigation:
    - title: "Accueil"
      url: "/"
    - title: "À propos"
      url: "/about/"
    - title: "Projets"
      url: "/projects/"
